### PR TITLE
Bugfixes, new icons

### LINKED ISSUE #267: Icons
**Describe the bug**
On iOS, the app added to home screen shows white parts around logo.
Icons everywhere don't look good. Change it all to a more white-on-black look? Rounded square also looks dull as a small favicon.

**To Reproduce**

1. Go to loop.page in safari
2. Add to desktop

**Additional context**
It's because it's loading the rounded logo and not the square one. Might need to change an apple-touch dimension.

### LINKED ISSUE #287: Extra space in modal
**Describe the bug**
Noticed on mobile, there was a block cut-out of empty space under the modal.

**To Reproduce**
Open a block with many cards

**Expected behavior**
It shouldn't be there, and instead should show the blocks.

### PR DESCRIPTION
**Pull request by nilaeus**
fixes #267
fixes #287

### CODE REVIEW

**Comment by nilaeus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/looppage/blocks/pullRequest?prid=5582949&bid=18299015)

File: public/serviceWorker.js [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+this.addEventListener('fetch', (event) => {
+  // request.mode = navigate isn't supported in all browsers
+  // so include a check for Accept: text/html header.
+  if (
+    event.request.mode === 'navigate' ||
+    (event.request.method === 'GET' &&
+      event.request.headers.get('accept').includes('text/html'))
+  ) {
+    event.respondWith(
+      fetch(event.request.url).catch((error) => {
```
Comment (nilaeus) [inline public/serviceWorker.js:25]: Codacy Issue found: ['error' is defined but never used.](https://app.codacy.com/gh/looppage/blocks/pullRequest?prid=5582949)

File: public/serviceWorker.js [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+      return cache.addAll(['/assets/donuts/192w/wb-circle.png', offlineUrl])
+    }),
+  )
+})
+this.addEventListener('fetch', (event) => {
+  // request.mode = navigate isn't supported in all browsers
+  // so include a check for Accept: text/html header.
+  if (
+    event.request.mode === 'navigate' ||
+    (event.request.method === 'GET' &&
```
Comment (nilaeus) [inline public/serviceWorker.js:21]: Codacy Issue found: [Delete `⏎·····`](https://app.codacy.com/gh/looppage/blocks/pullRequest?prid=5582949)
